using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace RussianRoullette
{
    public partial class Roullette : Form
    {
        Random Rnd = new Random();
        int shootTimes = 6;//shoot time variable
        int tryingGun = 2;//sets the value for try the gun
        public Roullette()
        {
            InitializeComponent();
        }

        private void btnLoad_Click(object sender, EventArgs e)
        {
            Assembly asmm = Assembly.GetExecutingAssembly();//An assembly is a file that is automatically generated by the compiler 
            pictureBox1.Image = RussianRoullette.Properties.Resources.load2;//image path to assign the variable
            System.Media.SoundPlayer soundPlayer = new System.Media.SoundPlayer(RussianRoullette.Properties.Resources.LoadingShotgun);//Add sound here
            soundPlayer.Play();//this is for playing the sound
            btnLoad.Enabled = false;//Here Buttonload will be disable after loading the gun
            BulletLooping.LoadingProcess = 1;//this variable is coming from static class
        }

        private void btnSpin_Click(object sender, EventArgs e)
        {
            Assembly asse = Assembly.GetExecutingAssembly();//An assembly is a file that is automatically generated by the compiler 
            pictureBox1.Image = RussianRoullette.Properties.Resources.spincham;//image path to assign the variable
            System.Media.SoundPlayer soundPlayer = new System.Media.SoundPlayer(RussianRoullette.Properties.Resources.LoadingShotgun);//Add sound here
            soundPlayer.Play();//this is for playing the sound

            btnSpin.Enabled = false;//Here Buttonspin will be disable after spinning the gun

            BulletLooping.SpinChamber = Rnd.Next(1, 6);//Random class variable
        }

        private void btnPlayAgain_Click(object sender, EventArgs e)
        {
            (new Roullette()).Show();
            this.Hide();
        }

        private void btnFire_Click(object sender, EventArgs e)
        {
            Assembly assm = Assembly.GetExecutingAssembly();//An assembly is a file that is automatically generated by the compiler 
            pictureBox1.Image = RussianRoullette.Properties.Resources.sshott;//Here i add the image on the picturebox
            System.Media.SoundPlayer soundPlayer = new System.Media.SoundPlayer(RussianRoullette.Properties.Resources.Shot);//Add sound here
            soundPlayer.Play();//play sound

            if (shootTimes > 0 && BulletLooping.SpinChamber == 1)
            {
                MessageBox.Show("You loose the Shoot");
                btnFire.Enabled = false;
            }
            else if (shootTimes > 0 && BulletLooping.SpinChamber != 1)
            {
                MessageBox.Show("This is Blank Fire");
                shootTimes = shootTimes - 1;//minus one from total
                BulletLooping.SpinChamber = BulletLooping.ShootTime(BulletLooping.SpinChamber);

            }
        }
    }
}
